config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :quadrants, only: :index

  get "quadrants/edit" => "quadrants#edit"
  match "quadrants/edit" => "quadrants#update", via: "PATCH"

end

app/views/layouts/home.html.haml
!!! 5
%html(lang="es")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : ""
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: "all"
    = favicon_link_tag('apple-touch-icon-144x144-precomposed.png',
      rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144')
    = favicon_link_tag('apple-touch-icon-114x114-precomposed.png',
      rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114')
    = favicon_link_tag('apple-touch-icon-72x72-precomposed.png',
      rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72')
    = favicon_link_tag('apple-touch-icon-precomposed.png',
      rel: 'apple-touch-icon-precomposed', type: 'image/png')
    = favicon_link_tag('favicon.ico', rel: 'shortcut icon')
    = javascript_include_tag "application"
    = javascript_include_tag "quadrants_edit" if @jsquadrants.present?
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

  %body
    .row
      .col-md-2
        #sidebar-wrapper
          %ul.sidebar-nav
            %li.sidebar-brand
              = link_to "#{app_name}", root_path
            %li
              = link_to "Ver cuadrante", quadrants_path
            %li
              = link_to "Editar cuadrante", quadrants_edit_path
      .col-md-10
        .container-fluid
          .row
            .col-xs-12
              = yield
          %footer.navbar.navbar-default.navbar-fixed-bottom
            .row
              .col-xs-12.text-center
                %p &copy; José Antonio Yáñez Jiménez – #{Date.today.year}